# Generated by Django 3.2 on 2025-03-14 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20250314_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, default=1, verbose_name='Биография'),
            preserve_default=False,
        ),
    ]
