# Generated by Django 3.2 on 2025-03-15 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_bio'),
        ('users', '0005_auto_20250315_1015'),
    ]

    operations = [
    ]
