# Generated by Django 3.2 on 2025-03-11 07:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='score',
            field=models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(0, message='Оценка должна быть от 1 до 10'), django.core.validators.MaxValueValidator(100, message='Оценка должна быть от 1 до 10')], verbose_name='Оценка'),
        ),
    ]
