# Generated by Django 3.2 on 2025-03-14 16:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_auto_20250313_0102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='year',
            field=models.SmallIntegerField(validators=[django.core.validators.MaxValueValidator(2025, message='Год не может быть больше текущего')], verbose_name='Год выпуска'),
        ),
    ]
